UPDATE public.site_settings SET logo_path = 'brand/divya-luxe-logo.jpg';

INSERT INTO public.services (gender, category, name, description, price, duration_minutes, sort_order) VALUES
('men','Hair','Kids Haircut','Gentle, patient styling for little ones under 12.',300,30,6),
('men','Hair','Hair Colour / Global Tone','Ammonia-free global colour with a glossing finish.',1500,90,7),
('men','Beard','Beard Colour','Natural-look beard colour with soft blending.',500,30,10),
('men','Beard','Hot Towel Shave','Classic razor shave with hot towel and after-balm.',400,30,11),
('men','Beard','Moustache Styling','Precision trim, shape and wax finish.',200,15,12),
('men','Skin','De-Tan Pack','Cooling de-tan treatment for face, neck and hands.',700,40,13),
('men','Skin','Charcoal Cleanup','Deep pore detox for oily and city-stressed skin.',600,30,14),
('men','Skin','Anti-Ageing Facial','Firming facial with collagen-rich serums.',1600,75,15),
('men','Spa','Head Massage','Warm oil scalp therapy to relieve tension.',400,30,16),
('men','Spa','Back & Shoulder Massage','Deep-tissue relief for desk-tight shoulders.',900,45,17),
('men','Spa','Hair Spa Ritual','Nourishing spa with steam and scalp massage.',1200,60,18),
('women','Hair','Keratin Smoothening','Frizz-control keratin for glass-smooth hair.',5500,180,6),
('women','Hair','Balayage / Highlights','Hand-painted dimension tailored to your tone.',4500,180,7),
('women','Beauty','Full Arms Waxing','Rica wax for smooth, soothed skin.',600,30,21),
('women','Beauty','Full Legs Waxing','Rica wax with a calming post-care gel.',900,45,22),
('women','Beauty','Threading & Shaping','Brow, upper lip and chin definition.',150,15,23),
('women','Beauty','Lash Lift & Tint','Lifted, tinted lashes with no extensions.',1800,60,24),
('women','Skin','Hydra Glow Facial','Hydration-boost facial for instant luminosity.',2200,75,25),
('women','Skin','Vitamin C Brightening','Antioxidant facial for even, radiant tone.',2000,60,26),
('women','Skin','Acne Care Treatment','Clinical-grade care for breakout-prone skin.',1800,60,27),
('women','Skin','Korean Glass Facial','Layered ritual for a dewy, poreless finish.',2800,90,28),
('women','Spa','Aroma Body Massage','Full-body relaxation with essential oils.',2500,75,29),
('women','Spa','Body Polishing','Exfoliating scrub and moisture wrap.',3000,90,30),
('women','Spa','Foot Reflexology','Pressure-point therapy for tired feet.',900,45,31),
('women','Spa','Hair Spa Ritual','Deep-conditioning spa with steam therapy.',1500,60,32),
('women','Nails','Nail Art (per hand)','Custom hand-painted art and finishes.',700,45,33),
('women','Nails','Gel Extensions','Sculpted gel extensions with a gloss top coat.',2500,120,34),
('women','Bridal','Engagement Makeup','Camera-ready look for your engagement day.',6000,120,35),
('women','Bridal','Reception Makeup','Glam evening look with lash and hair styling.',8000,150,36),
('women','Bridal','Mehendi Look','Fresh, vibrant styling for the mehendi ceremony.',4500,90,37),
('women','Bridal','Bridal Trial Session','Pre-wedding trial to lock in your final look.',3500,90,38);