update public.site_settings set
  phone = '+91 92265 64966',
  whatsapp = '+919226564966',
  address = 'Shop No. 506, Kanchan Trade Center, Devisha Road, Palghar (W), Tal & Dist - Palghar - 401404',
  hero_image_path = 'uploads/hero-salon.png',
  men_image_path = 'uploads/men-cover.png',
  women_image_path = 'uploads/women-cover.png',
  maps_embed_url = 'https://www.google.com/maps?q=Kanchan%20Trade%20Center%2C%20Devisha%20Road%2C%20Palghar%20West%2C%20401404&output=embed',
  updated_at = now();

delete from public.services;

insert into public.services (gender, category, name, description, price, offer_price, duration_minutes, badge, is_package, is_active, sort_order) values
('men','Hair','Signature Haircut','Consultation, precision cut and styling finish.',400,349,45,'Popular',false,true,1),
('men','Hair','Fade & Taper','Skin fade, taper or crop with clipper detailing.',350,null,40,null,false,true,2),
('men','Hair','Kids Haircut','Gentle cut for children under 12.',250,null,30,null,false,true,3),
('men','Hair','Hair Colour','Global colour or grey coverage with ammonia-free tint.',900,null,75,null,false,true,4),
('men','Hair','Hair Wash & Blow Dry','Deep cleanse, conditioning and blow-dry finish.',200,null,20,null,false,true,5),
('men','Beard','Beard Sculpt','Line-up, shaping and beard oil finish.',250,null,30,null,false,true,6),
('men','Beard','Royal Shave','Hot towel, luxury lather and straight-razor shave.',400,349,40,'Signature',false,true,7),
('men','Beard','Beard Colour','Natural-look beard tint with grey coverage.',350,null,30,null,false,true,8),
('men','Beard','Beard Spa','Steam, scrub and nourishing beard mask.',450,null,35,null,false,true,9),
('men','Skin','Detan Cleanup','De-tan pack for face and neck with instant glow.',600,499,40,null,false,true,10),
('men','Skin','Men''s Facial','Deep-cleansing facial for oily and dull skin.',900,799,60,'Popular',false,true,11),
('men','Skin','Charcoal Face Detox','Charcoal mask therapy for congested skin.',750,null,45,null,false,true,12),
('men','Spa','Head Massage','Relaxing oil massage for scalp and shoulders.',350,null,30,null,false,true,13),
('men','Spa','Hair Spa','Deep-conditioning spa for dry or damaged hair.',800,699,50,null,false,true,14),
('men','Spa','Grooming Package','Haircut + beard sculpt + cleanup in one sitting.',1200,999,105,'Best value',true,true,15),
('women','Hair','Haircut & Style','Designer cut with blow-dry styling.',700,599,60,'Popular',false,true,1),
('women','Hair','Global Colour','Full-head ammonia-free colour with gloss finish.',2500,null,120,null,false,true,2),
('women','Hair','Balayage & Highlights','Hand-painted dimension tailored to your tone.',4500,3999,180,'Signature',false,true,3),
('women','Hair','Keratin Treatment','Frizz control and smoothing with lasting shine.',5000,4499,180,null,false,true,4),
('women','Hair','Blow Dry & Styling','Wash, blow-dry and curls or straightening.',600,null,45,null,false,true,5),
('women','Skin','Luxury Facial','Brightening facial with massage and mask therapy.',1500,1299,75,'Popular',false,true,6),
('women','Skin','Cleanup','Quick cleanse, exfoliation and hydration.',700,null,40,null,false,true,7),
('women','Skin','Hydra Glow Facial','Intense hydration ritual for a dewy finish.',2200,1899,90,null,false,true,8),
('women','Beauty','Full Body Waxing','Rica or chocolate wax, full body.',1800,1599,90,null,false,true,9),
('women','Beauty','Threading','Eyebrows, upper lip and forehead.',100,null,15,null,false,true,10),
('women','Beauty','Face De-Tan Pack','Even tone and instant brightness.',600,null,35,null,false,true,11),
('women','Nails','Classic Manicure','Shape, cuticle care and polish.',500,null,40,null,false,true,12),
('women','Nails','Spa Pedicure','Soak, scrub, massage and polish.',800,699,55,null,false,true,13),
('women','Nails','Gel Polish','Long-wear gel colour with cure finish.',900,null,50,null,false,true,14),
('women','Nails','Nail Extensions','Acrylic or gel extensions with shaping.',1800,null,90,null,false,true,15),
('women','Nails','Nail Art','Custom art per nail by our artist.',150,null,20,null,false,true,16),
('women','Spa','Hair Spa Ritual','Deep-conditioning spa with scalp massage.',1200,999,60,null,false,true,17),
('women','Spa','Hair Treatment','Targeted repair for damage and hair fall.',1500,null,70,null,false,true,18),
('women','Bridal','Party Makeup','HD makeup with hairstyling and draping.',3500,2999,120,null,false,true,19),
('women','Bridal','Bridal Glow Package','Pre-bridal facials, polish, makeup and hair.',15000,12999,300,'Best value',true,true,20);